> 흥달쌤의 꺠알 자바 특강을 듣고 정리합니다.

# 객체&인스턴스

## 객체지향 프로그래밍

멤버변수와 메서드를 같이 묶어서 정의한 것이 객체!

객체의 속성과 행동을 묶어서 하나로 만든 것이다

객체가 어떤 행동을 하느냐에 따라서 속성의 값이 변경되게 된다.

## 객체 정의

붕어빵 틀을 만드는 것이다.

```java
public class Person{ // 객체 이름 Person
	String name = "25"; // 멤버변수1 선언
	int age = 40; //멤버변수2 선언

	public void setName(String n) { //메서드=행동
		name = n;
	}
	public void setAge(int i){ //메서드=행동
		age = 1;
	}
}
```

## 객체 생성

### 객체와 인스턴스의 차이점

객체라는 붕어빵 틀에서 찍어낸 것이 인스턴스

```java
public class Person{

	public static void main(String[] args){
		Person p1 = new Person();
		// p1이라는 인스턴스 생성
		// name과 age가 들어있게 된다.
		// 메서드 두가지도 들어있다.

		p1.set_name("25"); //메서드 호출
		p1.set_age(40); //메서드 호출
	}
}
```

## 멤버변수 & 메서드

### 멤버변수

객체에 정의된 속성값

`접근지정자 데이터타입 변수명;`

1. 이 변수에 누가 접근할 수 있는가
   - public
   - private
   - default
   - protected
2. 데이터타입
   - 변수에 들어갈 수 있는 데이터의 크기
   - String int 등
3. 변수명

```java
인스턴스명.멤버변수명 = 값;
p1.age = 40;
```

private은 이렇게 사용할 수 없다

### 메서드

객체에 정의된 행동 C언어에서는 함수에 해당한다

`접근지정자 리턴타입 메서드명(인자){ 하려고하는일 }`

void는 리턴타입이 없다

```java
public String get_name(){
	return this.name;
}
private void set_age(int age){
	this.age = age;
}

p1.set_name("홍길동"); //호출
```

## 데이터타입

메모리의 크기가 한정적이기 때문이다.

# 생성자

### 생성자란?

어떤 일을 시작하기 전에 준비를 하는 것.

new 해서 인스턴스가 생길 때 기본적으로 생기는 일들 정의

메서드랑 비슷한데 클래스랑 같은 이름인 것

```java
public class Person { // 하나의 객체 안에는 여러개의 생성자가 있을 수 있다.
	String name; // 멤버변수
	int age; // 멤버변수

	public Person(){ //생성자(인자)
		//인자 없이 객체를 호출할 때
		//person A = new Person();
		this.name = "사람"; //나의 name에 사람을 넣어라
		this.age = 1; //나의 age에 1을 넣어라
	}

	public Person(String name, int age) { //생성자(인자)
	// 인자 2개 생성자를 호출할 때
	// Person P = new Person("이", 1);
		this.name = name; //인자로 받은 걸 넣는다
		this.age = age; //인자로 받은 걸 넣는다
	}

}

public static void main(String[] args)
{
	Person p1 = new Person();
	//인자를 안 주면 인자 없는 게 호출된다 기본으로 사람과 1이 호출됨
	p1.toPrint();

	Person p2 = new Person("이흥직", 40);
	//인자 있는 생성자 호출
	p2.toPrint();
}
```

### EX

```java
class Ref{ //클래스
	int a;
	Ref(int x){ //생성자
		a = x; //this.a = x; 라고 쓰는 것이 정확하다
	}
}
	int sum(Ref obj){ //메서드. 아래에서 obj1을 인자로 넘겨받았다
		int k; //k라는 정수형 변수 생성
		k = obj.a-a; //obj1.a엔 3이 있고, a는 (obj2.sum이니까) obj2의 a (내가 가지고 있는 4값). 따라서 -1
		a = 10; obj.a = 20; //obj2의 a값을 10으로. obj1의 a값을 20으로.
		return k; // -1
	}
}
class PassRef {
	public static void main(String args[]){
		Ref obj1 = new Ref(3); //인자값 3이 인스턴스 obj1의 멤버변수 a에 들어간다
		Ref obj2 = new Ref(4); //인자값 4이 인스턴스 obj2의 멤버변수 a에 들어간다
		int k1= obj2.sum(obj1); //obj2의 메서드 sum 호출. obj1을 sum의 인자로 넘겨준다. 따라서 해당 메서드의 this = obj2다.
		System.out.print(" obj1.a = " + obj1.a) //20
		System.out.print(" obj2.a = " + obj2.a) //10
	}
}
```

# 예외

예기치 못한 오류에 대한 처리

```java
public static void main(String[] args) {
	try{
		//코드실행
	}
	catch(ArithmeticException e){
		//산술계산 오류발생시 실행 ex. 10/0같은 것
	}
	catch(Exception e){
		//모든 오류 발생시 실행
	}
	finally{ //안 써도 됨. 써있으면 무조건 실행한다.
		//모든 오류처리가 종료된 후 실행
		//객체를 닫는다거나 반환할 때 많이 사용한다
	}
}
```

catch문은 여러개 만들 수 있다

여러가지 예외가 발생할 수 있기 때문이다

DB연결할 때 사용한다.

### 메인 함수 안에서 구현하기

```java
public static void main(String[] args) {
	int a = 10;
	int b = 2;
	try {
		System.out.println("Start");
		System.out.println(" "+(a/b));,
		System.out.println("End");
		//결과값은 5입니다. + 엔터
	}
	catch(ArithmeticException e){
		//0으로 나누게 되면 오류가 발생. 프로그램 중단하고 예외처리로 들어온다.
		System.out.println("산술오류 발생");
	}
	catch(Exception e){
		//모든 오류가 발생했을 때
		System.out.println("오류 발생");
	}
	finally{ //무조건 최종 실행
		System.out.println("프로그램 종료");
		//프로그램 종료 + 엔터
	}
}
```

예외 만나고나면 다시 올라갈 수 없다. catch로 빠지고 finally로 빠지게 된다.

### EX

```java
public static void foo() throws Exception{
	try{
		System.out.println("E");
		throw new Exception();
	}
	catch(Exception e){
		System.out.println("F");
		throw e;
	}
	finally {
		System.out.println("G");
	}
}
public static void main(String[]){
	// 일단 메인 함수로 간다
	try {
		System.out.println("문장 A");
		foo();
		System.out.println("문장 B");
	}
	catch(Exception e){
		System.out.println("문장 C");
	}
	System.out.println("문장 D");
}
```

1. 문장 A 출력
2. 메서드 foo 실행
   1. **throws Exception** 예외를 던져라 (나를 호출한 곳으로)
3. 문장 E 출력
4. **throw Exception** 예외를 만들어버린다 = 즉 예외 발생
5. catch로 간다 문장 F 출력
6. throw e는 아무 의미 없다
7. finally 문장 G 출력
8. 다시 돌아와서 문장 B 출력
9. 예외 발생 안했으니 문장 D 출력

```java
public static void foo() throws Exception{
// 내가 예외처리하지 않고 나를 호출한 곳에 보낼거야. 니가 대신 예외처리해줘!
		System.out.println("E");
		throw new Exception();
}
public static void main(String[]){
	// 일단 메인 함수로 간다
	try {
		System.out.println("문장 A");
		foo();
		System.out.println("문장 B");
	}
	catch(Exception e){
		System.out.println("문장 C");
	}
	System.out.println("문장 D");
}
```

1. 문장 A 출력
2. 문장 E 출력
3. 예외 발생
4. main으로 돌아가서 catch 실행 문장 C 출력
5. 문장 D 출력
